import type { Metadata } from "next";
import "@/styles/globals.css";
import {Box, Container} from "@mui/material";
import BgOverlay from "@/components/bg-overlay";

export const metadata: Metadata = {
  title: "Game Search",
  description: "Generated by create next app",
};

export default async function ErrorLayout({children}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      <BgOverlay imageName={'/images/games_bg.jpg'}/>
      <Box
        alignItems="center"
        justifyContent="center"
        display="flex"
        width='100vw'
        height='100vh'
      >
        <Container maxWidth="sm">
          {children}
        </Container>
      </Box>
    </>
  );
}