import type { Metadata } from "next";
import "@/styles/globals.css";
import Providers from "@/lib/Providers";
import {Container} from "@mui/material";


export const metadata: Metadata = {
  title: "Game Search",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body>
        <Providers>
            <Container maxWidth="lg" sx={{minHeight: '100vh'}}>
                {children}
            </Container>
        </Providers>
      </body>
    </html>
  );
}
