import type { Metadata } from "next";
import "@/styles/globals.css";
import Providers from "@/lib/Providers";
import {Box, Container, Stack} from "@mui/material";
import Header from "@/components/header";


export const metadata: Metadata = {
  title: "Game Search",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body>
        <Providers>
            <Container
              maxWidth="lg"
              sx={{
                minHeight: '100vh',
                padding: 2,
              }}>
              <Stack>
                <Header/>
                <Box sx={{ height: 24 }} />
                {children}
              </Stack>
            </Container>
        </Providers>
      </body>
    </html>
  );
}
