import type { Metadata } from "next";
import "@/styles/globals.css";
import ContainerLayout from "@/lib/ContainerLayout";

export const metadata: Metadata = {
  title: "Game Search",
  description: "Generated by create next app",
};

export default async function DevelopersLayout({children}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ContainerLayout>
      {children}
    </ContainerLayout>
  );
}